Switching from tabs to spaces

diff --git a/util/bin/setup_repository b/util/bin/setup_repository
--- a/util/bin/setup_repository
+++ b/util/bin/setup_repository
@@ -6,36 +6,36 @@ GIT_DIR_UID=$(stat -c %u .git/ 2> /dev/null || stat -f "%u" .git/)
 GIT_DIR_USER=$(stat -c %U .git/ 2> /dev/null || stat -f "%Su" .git/)
 
 if [ "$UID" != "$GIT_DIR_UID" ]; then
-	echo "ERROR!"
-	echo "You need to be the same user as the owner of the .git directory."
-	echo "If you are using sudo, you shouldn't.  Become $GIT_DIR_USER"
-	exit 1
+    echo "ERROR!"
+    echo "You need to be the same user as the owner of the .git directory."
+    echo "If you are using sudo, you shouldn't.  Become $GIT_DIR_USER"
+    exit 1
 fi
 
 function setup_symlink() {
-	local DESTDIR
-	local DESTFILE
-	local TARGET
+    local DESTDIR
+    local DESTFILE
+    local TARGET
 
-	DESTDIR=$1
-	DESTFILE=$2
-	TARGET=$3
+    DESTDIR=$1
+    DESTFILE=$2
+    TARGET=$3
 
-	echo_prompt "$DESTDIR$DESTFILE:  "
-	cd "$DESTDIR"
+    echo_prompt "$DESTDIR$DESTFILE:  "
+    cd "$DESTDIR"
 
-	if [ "$(readlink "$DESTFILE")" != "$TARGET" ]; then
-		rm -rf "$DESTFILE"
-		ln -s "$TARGET" "$DESTFILE"
+    if [ "$(readlink "$DESTFILE")" != "$TARGET" ]; then
+        rm -rf "$DESTFILE"
+        ln -s "$TARGET" "$DESTFILE"
 
-		if [ $? -eq 0 ]; then
-			echo "Set up symbolic link"
-		else
-			echo "Unable to make the symbolic link"
-		fi
-	else
-		echo "Already done"
-	fi
+        if [ $? -eq 0 ]; then
+            echo "Set up symbolic link"
+        else
+            echo "Unable to make the symbolic link"
+        fi
+    else
+        echo "Already done"
+    fi
 }
 
 run_all_scripts "util/helpers/setup.d"
diff --git a/util/git/hooks/pre-commit b/util/git/hooks/pre-commit
--- a/util/git/hooks/pre-commit
+++ b/util/git/hooks/pre-commit
@@ -6,12 +6,12 @@
 
 # Determine the revision we are comparing against
 if git rev-parse --verify HEAD 1>/dev/null 2>&1; then
-	AGAINST=HEAD
-	debug "Diffing against head"
+    AGAINST=HEAD
+    debug "Diffing against head"
 else
-	# Initial commit: diff against an empty tree object
-	AGAINST=4b825dc642cb6eb9a060e54bf8d69288fbee4904
-	debug "Diffing against an empty commit"
+    # Initial commit: diff against an empty tree object
+    AGAINST=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+    debug "Diffing against an empty commit"
 fi
 
 # Iterate over each file that is being committed
@@ -19,40 +19,40 @@ ERROR_COUNT=0
 RESULT=0
 
 while read FILE; do
-	# Show we are doing something to a file
-	echo_prompt "$FILE"
+    # Show we are doing something to a file
+    echo_prompt "$FILE"
 
-	FILE_IGNORED=false
-	FILE_DELETED=true
+    FILE_IGNORED=false
+    FILE_DELETED=true
 
-	# See if the file was deleted
-	if [[ -f "$FILE" && ! -h "$FILE" ]]; then
-		FILE_DELETED=false
-	else
-		debug "Detected $FILE was deleted"
-	fi
+    # See if the file was deleted
+    if [[ -f "$FILE" && ! -h "$FILE" ]]; then
+        FILE_DELETED=false
+    else
+        debug "Detected $FILE was deleted"
+    fi
 
-	for DIR in $IGNORE_DIRS; do
-		if [[ "$FILE" = $DIR* ]]; then
-			FILE_IGNORED=true
-			debug "Detected $FILE is to be ignored"
-		fi
-	done
+    for DIR in $IGNORE_DIRS; do
+        if [[ "$FILE" = $DIR* ]]; then
+            FILE_IGNORED=true
+            debug "Detected $FILE is to be ignored"
+        fi
+    done
 
-	run_all_scripts util/git/pre-commit.d/
+    run_all_scripts util/git/pre-commit.d/
 
-	if [ $? -ne 0 ]; then
-		: $((ERROR_COUNT++))
-	fi
+    if [ $? -ne 0 ]; then
+        : $((ERROR_COUNT++))
+    fi
 
-	# Clear away the current file
-	echo_clear_line
+    # Clear away the current file
+    echo_clear_line
 done < <(git diff-index --name-only --cached $AGAINST)
 
 if [ $ERROR_COUNT -ne 0 ]; then
-	echo ""
-	echo "Correct any errors and commit again."
-	exit 1
+    echo ""
+    echo "Correct any errors and commit again."
+    exit 1
 fi
 
 exit 0
diff --git a/util/helpers/setup.d/git-submodule b/util/helpers/setup.d/git-submodule
--- a/util/helpers/setup.d/git-submodule
+++ b/util/helpers/setup.d/git-submodule
@@ -1,20 +1,20 @@
 #!/bin/bash
 
 if [ -f .gitmodules ]; then
-	echo_prompt "git submodules: "
+    echo_prompt "git submodules: "
 
-	git submodule init > /dev/null 2>&1
+    git submodule init > /dev/null 2>&1
 
-	if [ $? -ne 0 ]; then
-		echo "Error running 'git submodule init'"
-	else
-		git submodule update > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        echo "Error running 'git submodule init'"
+    else
+        git submodule update > /dev/null 2>&1
 
-		if [ $? -ne 0 ]; then
-			echo "Error running 'git submodule update'"
-		else
-			echo "Ok"
-		fi
-	fi
+        if [ $? -ne 0 ]; then
+            echo "Error running 'git submodule update'"
+        else
+            echo "Ok"
+        fi
+    fi
 fi
 
