Consolidated symlink setup code

diff --git a/util/bin/setup_repository b/util/bin/setup_repository
--- a/util/bin/setup_repository
+++ b/util/bin/setup_repository
@@ -10,4 +10,30 @@ if [ "$UID" != "$(stat -c %u .git/)" ]; then
 	exit 1
 fi
 
+function setup_symlink() {
+	local DESTDIR
+	local DESTFILE
+	local TARGET
+
+	DESTDIR="$1"
+	DESTFILE="$2"
+	TARGET="$3"
+
+	echo_prompt "$DESTDIR$DESTFILE:  "
+	cd "$DESTDIR"
+
+	if [ "$(readlink "$DESTFILE")" != "$TARGET" ]; then
+		rm -rf "$DESTFILE"
+		ln -s "$TARGET" "$DESTFILE"
+
+		if [ $? -eq 0 ]; then
+			echo "Set up symbolic link"
+		else
+			echo "Unable to make the symbolic link"
+		fi
+	else
+		echo "Already done"
+	fi
+}
+
 run_all_scripts util/helpers/setup.d
